### ISSUE TITLE
Update README.md for Sphinx documentation

### ISSUE THREAD

**Issue by astrochun** [UAL-ODIS/redata-commons#9]
With docs published on ReadTheDocs, here are a few necessary changes to minimize docs maintainence.

- [x] Make the README.md concise. Only keep the most important item
- [x] Have a TOC that points to separate sections of the ReadTheDocs pages
- [x] Include GitHub badges for
   - [x] RTDs build status
   - [x] GitHub Actions Sphinx build status

**Notes**

RTD Build status badges cannot be fully customized. This means that (1) the label will always be called `docs`, and that (2) the color will always reflect the build status (green, red, etc.). In fewer words: we cannot make the RTDs badge style match the other ReDATA badges.

For documentation see: 
https://docs.readthedocs.io/en/stable/badges.html#status-badges
and https://raw.githubusercontent.com/readthedocs/readthedocs.org/master/docs/badges.rst

**Implemented in:** docs/09_README

**Comment by damian-romero** [comment]
An issue with RTD badges: 

RTDs badges are not fully customizable (see description above). For this reason, I had to name the label of the `GitHub Actions Sphinx build status` as `sphinx`, instead of `docs` (which would conflict with the RTDs badge). 

Notice that this introduces a discrepancy with [ReQUIAM_csv,](https://github.com/UAL-ODIS/ReQUIAM_csv/blob/master/README.md) where the Sphinx build badge is labeled `docs`. We may want to update badges across all our repositories at some point.

**Comment by astrochun** [comment]
> An issue with RTD badges:
> 
> RTDs badges are not fully customizable (see description above). For this reason, I had to name the label of the `GitHub Actions Sphinx build status` as `sphinx`, instead of `docs` (which would conflict with the RTDs badge).

Their badge is not, but there are ways with shields.io to customize it. I did it for another [repo](https://github.com/astrochun/Metallicity_Stack_Commons). Here's what I did:
```
[![Read the Docs](https://img.shields.io/readthedocs/metallicity-stack-commons?color=blue&label=RTDs)](https://readthedocs.org/projects/metallicity-stack-commons/builds/)
```

> 
> Notice that this introduces a discrepancy with [ReQUIAM_csv,](https://github.com/UAL-ODIS/ReQUIAM_csv/blob/master/README.md) where the Sphinx build badge is labeled `docs`. We may want to update badges across all our repositories at some point.
